// File generated by GitHub Copilot automatically from google-services.json

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions has not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnFHdMw4PhHj81mY9gx2cqCDun5J-NCSo',
    appId: '1:10908876468:android:2e9311a55780a9602961e1',
    messagingSenderId: '10908876468',
    projectId: 'ewumatefcm',
    storageBucket: 'ewumatefcm.firebasestorage.app',
  );
}
